version: '3'
services:
  cnil-pia-back:
    build: docker/cnil-pia-back
    restart: always
    environment:
      DATABASE_HOST: 'database'
      DATABASE_USERNAME: 'postgres'
      DATABASE_PASSWORD: 'pia-test'
      SECRET_KEY_BASE: 'a3155b0aae4087e828b2214ac06a905a61ed6ca2825795b9278a541fe431d6198acf8f561b88e0cf2191e572a9f3f387ed00c4e2d45e52cd1b41e73fee58f758'
    links:
      - database
    depends_on:
      - database
    ports:
      - 3000:3000

  cnil-pia-front:
    build: docker/cnil-pia-front
    restart: always
    ports:
      - 0.0.0.0:8080:80

  database:
    image: postgres:10.1
    restart: always
    environment:
      POSTGRES_PASSWORD: 'pia-test'
